version: 2.0
jobs:
  build:
    docker:
      - image: gradle:jdk11
    steps:
      - checkout:
      - run:
          ci/build-app.sh
      - run:
          - ci/unit-test-app.sh
      - store_test_results:
          path: test-results.xml
